-- 清单管理模块：非遗项目分类、非遗项目、传承人等
USE heritage_management;

-- 非遗项目分类表：管理非遗项目分类
CREATE TABLE heritage_category (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '分类唯一标识，自增主键',
    category_name VARCHAR(100) NOT NULL COMMENT '分类名称',
    parent_id BIGINT DEFAULT 0 COMMENT '父分类ID，0表示顶级分类',
    category_level TINYINT DEFAULT 1 COMMENT '分类级别',
    sort_order INT DEFAULT 0 COMMENT '排序顺序',
    status TINYINT DEFAULT 1 COMMENT '状态：1-显示，0-隐藏',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
    created_by BIGINT COMMENT '创建人ID',
    updated_by BIGINT COMMENT '更新人ID',
    del_flag TINYINT DEFAULT 0 COMMENT '逻辑删除标志：0-未删除，1-已删除',
    deleted_at DATETIME COMMENT '删除时间',
    deleted_by BIGINT COMMENT '删除人ID',
    remark VARCHAR(255) COMMENT '备注',
    INDEX idx_parent_id (parent_id) COMMENT '父分类ID索引',
    INDEX idx_sort_order (sort_order) COMMENT '排序顺序索引',
    INDEX idx_status (status) COMMENT '状态索引',
    INDEX idx_del_flag (del_flag) COMMENT '删除状态索引'
) COMMENT '非遗项目分类表，管理非遗项目分类';

-- 非遗项目表：管理非遗项目信息
CREATE TABLE heritage_project (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '项目唯一标识，自增主键',
    project_name VARCHAR(200) NOT NULL COMMENT '项目名称',
    project_code VARCHAR(50) COMMENT '项目编号',
    category_id BIGINT COMMENT '分类ID，外键关联heritage_category表',
    declaration_area VARCHAR(100) COMMENT '申报地区',
    declaration_level TINYINT COMMENT '申报级别：1-区级，2-州级，3-省级，4-国家级',
    declaration_batch VARCHAR(50) COMMENT '申报批次',
    declaration_year INT COMMENT '申报年份',
    approval_number VARCHAR(100) COMMENT '批准文号',
    approval_date DATE COMMENT '批准日期',
    is_unesco TINYINT DEFAULT 0 COMMENT '是否联合国教科文组织名录：0-否，1-是',
    unesco_year INT COMMENT '入选联合国教科文组织年份',
    unesco_category VARCHAR(100) COMMENT '联合国教科文组织类别',
    cover_image VARCHAR(255) COMMENT '封面图片',
    project_desc TEXT COMMENT '项目描述',
    protection_status TEXT COMMENT '保护现状',
    historical_origin TEXT COMMENT '历史渊源',
    cultural_space TEXT COMMENT '文化空间',
    inheritance_mode TEXT COMMENT '传承方式',
    social_value TEXT COMMENT '社会价值',
    protection_measures TEXT COMMENT '保护措施',
    view_count INT DEFAULT 0 COMMENT '浏览次数',
    status TINYINT DEFAULT 1 COMMENT '状态：1-显示，0-隐藏',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
    created_by BIGINT COMMENT '创建人ID',
    updated_by BIGINT COMMENT '更新人ID',
    del_flag TINYINT DEFAULT 0 COMMENT '逻辑删除标志：0-未删除，1-已删除',
    deleted_at DATETIME COMMENT '删除时间',
    deleted_by BIGINT COMMENT '删除人ID',
    remark VARCHAR(255) COMMENT '备注',
    INDEX idx_project_name (project_name) COMMENT '项目名称索引',
    INDEX idx_project_code (project_code) COMMENT '项目编号索引',
    INDEX idx_category_id (category_id) COMMENT '分类ID索引',
    INDEX idx_declaration_level (declaration_level) COMMENT '申报级别索引',
    INDEX idx_declaration_year (declaration_year) COMMENT '申报年份索引',
    INDEX idx_is_unesco (is_unesco) COMMENT '是否联合国教科文组织名录索引',
    INDEX idx_status (status) COMMENT '状态索引',
    INDEX idx_del_flag (del_flag) COMMENT '删除状态索引'
) COMMENT '非遗项目表，管理非遗项目信息';

-- 传承人表：管理非遗传承人信息
CREATE TABLE heritage_inheritor (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '传承人唯一标识，自增主键',
    inheritor_name VARCHAR(100) NOT NULL COMMENT '传承人姓名',
    gender TINYINT COMMENT '性别：1-男，2-女',
    birth_date DATE COMMENT '出生日期',
    nation VARCHAR(50) COMMENT '民族',
    native_place VARCHAR(100) COMMENT '籍贯',
    id_card VARCHAR(18) COMMENT '身份证号',
    contact_phone VARCHAR(20) COMMENT '联系电话',
    address VARCHAR(255) COMMENT '联系地址',
    project_id BIGINT COMMENT '所属项目ID，外键关联heritage_project表',
    inheritor_level TINYINT COMMENT '传承人级别：1-区级，2-州级，3-省级，4-国家级',
    approval_number VARCHAR(100) COMMENT '批准文号',
    approval_date DATE COMMENT '批准日期',
    approval_batch VARCHAR(50) COMMENT '批准批次',
    avatar VARCHAR(255) COMMENT '头像',
    inheritor_desc TEXT COMMENT '传承人介绍',
    skill_desc TEXT COMMENT '技艺特点',
    inheritance_mode TEXT COMMENT '传承方式',
    inheritance_achievement TEXT COMMENT '传承成果',
    status TINYINT DEFAULT 1 COMMENT '状态：1-显示，0-隐藏',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
    created_by BIGINT COMMENT '创建人ID',
    updated_by BIGINT COMMENT '更新人ID',
    del_flag TINYINT DEFAULT 0 COMMENT '逻辑删除标志：0-未删除，1-已删除',
    deleted_at DATETIME COMMENT '删除时间',
    deleted_by BIGINT COMMENT '删除人ID',
    remark VARCHAR(255) COMMENT '备注',
    INDEX idx_inheritor_name (inheritor_name) COMMENT '传承人姓名索引',
    INDEX idx_project_id (project_id) COMMENT '所属项目ID索引',
    INDEX idx_inheritor_level (inheritor_level) COMMENT '传承人级别索引',
    INDEX idx_status (status) COMMENT '状态索引',
    INDEX idx_del_flag (del_flag) COMMENT '删除状态索引'
) COMMENT '传承人表，管理非遗传承人信息';